export const PROJECTS = {
  flagship: [
    {
      id: "la-citadel",
      title: "La Citadel",
      category: "Ultra-Luxury Villas",
      location: "Vizag",
      acres: "50 Acres",
      area: "15,00,000 Sq Ft",
      image: "/Project Images/LAcitadelid1.png",
    },
    {
      id: "sanctuary",
      title: "Sanctuary by Palm Exotica",
      category: "Luxury Farm Community",
      location: "Shankarpalli",
      acres: "180 Acres",
      area: "9,00,000 Sq Yards",
      image: "/Project Images/Sanctuary1.png",
    },
    {
      id: "pv-sindhu",
      title: "PV Sindhu Badminton Academy",
      category: "Sports Academy",
      location: "Vizag",
      acres: "3 Acres",
      area: "2,25,000 Sq Ft",
      image: "/Project Images/PVsportsacademy.png",
    },
    {
      id: "itc-welcome",
      title: "ITC Welcome Palm Exotica Resorts",
      category: "Luxury Five Star Resort",
      location: "Hyderabad",
      acres: "12 Acres",
      area: "3,00,000 Sq Ft",
      image: "/Project Images/ITCid1.png",
    },
    {
      id: "Parcville",
      title: "Parcville",
      category: "Villa Community",
      location: "Vijayawada",
      acres: "12 Acre",
      area: "6,50,000 Sq Ft",
      image: "/Project Images/Corporateofc1.png",
    },
    {
      id: "VPR Shantiniketham",
      title: "VPR Shantiniketham",
      category: "Luxery Villas",
      location: "nellore",
      acres: "10 Acres",
      area: "3,50,000 Sq Ft",
      image: "/Project Images/Aivista1.png",
    },
    {
      id: "Pheonix",
      title: "Phoenix Centaurus",
      category: "IT SEZ",
      location: "Nanakramguda",
      acres: "3 Acres",
      area: "17,00,000 Sq Ft",
      image: "/Project Images/Nexus1.png",
    },
    {
      id: "concrete Capital",
      title: "Concrete Capital",
      category: "G+14 Commercial Building",
      location: "Gachibowli",
      acres: "1 Acres",
      area: "3,00,000 Sq Ft",
      image: "/Project Images/Concrete331.png",
    },
  ],
  ongoing: [
    {
      id: 1,
      title: "Sanctuary by Palm Exotica",
      category: "Luxury Farm Community",
      location: "Shankarpally",
      siteArea: "180 acres",
      builtArea: "9,00,000 sq yds",
      image: "/Project Images/Sanctuary1.png",
      image1: "/Project Images/Sanctuaryid2.png"
    },
    {
      id: 2,
      title: "La Citadel",
      category: "Ultra-Luxury Villas",
      location: "Visakhapatnam",
      siteArea: "50 Acres",
      builtArea: "15,00,000 sqft",
      image: "/Project Images/LAcitadelid1.png",
      image1: "/Project Images/LAcitadelid2.png",
    },
    {
      id: 3,
      title: "Concrete Capital",
      category: "Corporate Offices",
      location: "Nanakramguda",
      siteArea: "1 Acre",
      builtArea: "3,00,000 sqft",
      image: "/Project Images/Corporateofc1.png",
      image1: "/Project Images/Corporateofc1.png",
    },
    {
      id: 4,
      title: "PV Sindhu Badminton Academy",
      category: "Sports Academy",
      location: "Visakhapatnam",
      siteArea: "3 Acre",
      builtArea: "2,25,000 sqft",
      image: "/Project Images/PVsportsacademy.png",
      image1: "/Project Images/PVsportsacademy.png",
    },
    {
      id: 5,
      title: "ITC Welcome Palm Exotica Resorts",
      category: "Luxury Five Star Resort",
      location: "Hyderabad",
      siteArea: "12 Acres",
      builtArea: "3,00,000 sqft",
      image: "/Project Images/ITCid1.png",
      image1: "/Project Images/ITCid2.png",
    },
  ],
  upcoming: [
    {
      id: 1,
      title: "AirVista Hotel",
      category: "Boutique Star Hotel",
      location: "Tirupathi",
      siteArea: "3200 sq yards",
      builtArea: "1,20,000 sqft",
      image: "/Project Images/Aivista1.png",
      image1: "/Project Images/Aivista2.png",
    },
    {
      id: 2,
      title: "Nexus 1",
      category: "Luxury Apartments",
      location: "Hyderabad",
      siteArea: "3 Acres",
      builtArea: "300,000 sqft",
      image: "/Project Images/Nexus1.png",
      image1: "/Project Images/Nexus2.png",
    },
    {
      id: 3,
      title: "Concrete 33",
      category: "Highrise Apartments",
      location: "Hyderabad",
      siteArea: "4.3 Acres",
      builtArea: "21,00,000 sqft",
      image: "/Project Images/Concrete331.png",
      image1: "/Project Images/Concrete331.png",
    },
    {
      id: 4,
      title: "NCD Purple",
      category: "Highrise Apartments",
      location: "Hyderabad",
      siteArea: "4 Acres",
      builtArea: "800,000 sqft",
      image: "/Project Images/NCD purple1.png",
      image1: "/Project Images/NCD purple1.png",
    },
  ],
};

export const SERVICES = [
  {
    id: "design",
    title: "Design Services",
    description: "Transforming vision into executable design.",
    details: "Architecture services that capture imagination and translate it into precise, build-ready plans.",
    icon: "DraftingCompass",
  },
  {
    id: "transaction",
    title: "Transaction Management",
    description: "Strategic deal-making with precision foresight.",
    details: "Real estate consultancy ensuring optimal client deals with market intelligence and negotiation expertise.",
    icon: "Handshake",
  },
  {
    id: "contracting",
    title: "Contracting",
    subtitle: "(Civil & Finishes Construction)",
    description: "Engineering excellence meets execution mastery.",
    details: "Deploying advanced construction technologies and engineering practices for flawless civil and interior delivery.",
    icon: "HardHat",
  },
  {
    id: "pcms",
    title: "PCMS",
    subtitle: "(Project Construction Management Service)",
    description: "Strategic deal-making with precision foresight.",
    details: "Delivering on-time and within-budget management solutions through expert staffing and integrated supply chain services.",
    icon: "Settings2",
  },
  {
    id: "turnkey",
    title: "Turnkey Solutions",
    description: "Seamless delivery from concept to commissioning.",
    details: "Fully integrated solutions encompassing transaction, design, contracting, and construction management consultancy for efficient execution. Finalizing the transaction through lease or sale of the property, effectively closing the loop.",
    icon: "Key",
  },
];

export const COMPLETED_PROJECTS = [
  {
    year: "2017",
    projects: [
      {
        name: "Concrete Corporate",
        location: "Gachibowli",
        type: "Corporate Office",
        area: "900 Sq Yds | 30,000 Sq Ft",
      },
      {
        name: "Sybaritic Suites",
        location: "Gachibowli",
        type: "Corporate Office",
        area: "900 Sq Yds | 36,000 Sq Ft",
      },
    ],
  },
  {
    year: "2018",
    projects: [
      {
        name: "Residential Apartments, Pavilion 1",
        location: "Nallagandla",
        type: "",
        area: "400 sq yds | 12,500 sq. ft.",
      },
      {
        name: "Service Apartments, Pavilion 2",
        location: "Financial District",
        type: "",
        area: "500 sq yds | 13,500 sq. ft.",
      },
      {
        name: "Service Apartments, DMY Plaza",
        location: "Kokapet",
        type: "",
        area: "75,000 sq. ft",
      },
      {
        name: "VIP Residence, Konda Mansion",
        location: "Kodad",
        type: "",
        area: "2,000 sq. yds | 20,000 sq ft",
      },
    ],
  },
  {
    year: "2019",
    projects: [
      {
        name: "AP CM YS Jagan Residency",
        location: "Tadepalli",
        type: "",
        area: "1.5 Acre | 60,000 Sft",
      },
      {
        name: "YSRCP Party office",
        location: "Tadepalli",
        type: "",
        area: "1 Acre | 65,000 Sft",
      },
      {
        name: "The Out House, Bliss in the Woods",
        location: "Tukkuguda",
        type: "",
        area: "1 Acre | 3,000 sq ft",
      },
    ],
  },
  {
    year: "2020",
    projects: [
      {
        name: "Parcville, Vijayawada",
        location: "Villa Community",
        type: "",
        area: "12 Acre | 6,50,000 Sq Ft",
      },
      {
        name: "Parc Heights Ultra-Luxury Apartment",
        location: "Gated Community, Vijayawada",
        type: "",
        area: "0.62 Acres | 62,000 sq. ft.",
      },
    ],
  },
  {
    year: "2021",
    projects: [
      {
        name: "VPR Shantiniketan, Nellore",
        location: "Luxury Villas",
        type: "",
        area: "10 Acres | 3,50,000 Sq Ft",
      },
      {
        name: "TERI SAS",
        location: "Gachibowli",
        type: "",
        area: "5 Acre | 2,50,000 sq. ft",
      },
      {
        name: "Phoenix Centaurus, Wipro Circle",
        location: "External Development Works",
        type: "",
        area: "5 Acre | Entry Portal",
      },
    ],
  },
  {
    year: "2022",
    projects: [
      {
        name: "Phoenix P285 FD, Nanakramguda",
        location: "IT SEZ",
        type: "External Development Works",
        area: "25 Acre | Entrance Portal",
      },
      {
        name: "Farm House, Twin Farms",
        location: "Hyderabad",
        type: "",
        area: "40 acre | 60,000 sqft",
      },
      {
        name: "Luxury Villa Community, Sai Vishnu Villas Chaturvatika",
        location: "Ongole",
        type: "",
        area: "50 Acre | 10,00,000+ sq. ft.",
      },
    ],
  },
  {
    year: "2023",
    projects: [
      {
        name: "Vascular Hospital",
        location: "Hyderabad",
        type: "",
        area: "1,200 sq yds | 46,000 sq ft",
      },
      {
        name: "VIP Residence, 13 Banjara",
        location: "Hyderabad",
        type: "",
        area: "350 sq yds | 12,000 sq ft",
      },
      {
        name: "Service Apartments, Pavilion 3",
        location: "Gachibowli",
        type: "",
        area: "380 sq yds | 11,000 sq. ft.",
      },
      {
        name: "Sanctuary by Palm Exotica Phase 1",
        location: "Shankarpally",
        type: "",
        area: "120 Acre | 5,80,000 Sq Yard",
      },
    ],
  },
  {
    year: "2024",
    projects: [
      {
        name: "Concrete Avasa",
        location: "Chandanagar",
        type: "",
        area: "3 Acre | 3,75,000 sq ft",
      },
      {
        name: "DSR Mansion",
        location: "Tuni",
        type: "",
        area: "3,000 Sq Yards | 35,000 Sft",
      },
      {
        name: "DSR Party Office",
        location: "Tuni",
        type: "",
        area: "500 Sq Yards | 20,000 Sft",
      },
      {
        name: "Harsha Icon",
        location: "Gachibowli",
        type: "Corporate Fitout",
        area: "10,000 Sft",
      },
      {
        name: "Dhammam Infra",
        location: "Financial District",
        type: "Corporate Fitout",
        area: "11,500 Sft",
      },
      {
        name: "Service Apartments, Pavilion 3",
        location: "DLF Gachibowli",
        type: "",
        area: "300 sq yds | 10,000 sq. ft.",
      },
      {
        name: "Service Apartments, Pavilion 4",
        location: "Telecom Nagar",
        type: "",
        area: "500 Sq yds | 14,000 Sft",
      },
    ],
  },
];

export const STATS = [
  { value: "50,00,000+", label: "Sq Ft Delivered" },
  { value: "100+", label: "Projects Completed" },
  { value: "5+", label: "Cities Presence" },
  { value: "15+", label: "Years Excellence" },
];

export const LEADERSHIP = {
  name: "Mr. Kartheek Chukkapalli",
  role: "Managing Director",
  credentials: [
    "PMP",
    "PGDM",
    "Oracle Certified Professional",
    "SAP CRM Certified",
    "CLM",
    "Marketing 3.0 Professional",
    "Honorary Doctorate in Project Management USAIU",
  ],
  bio: "Mr. Kartheek’s leadership isn’t just about management, it’s about envisioning possibilities, orchestrating complexities, and delivering excellence. His strategic foresight and technical mastery position the organization as a leader in delivering mega-projects.",
  experience: "10 Years delivering projects exceeding 50,00,000 sq ft",
  associations: ["BNI", "IACC", "WZBA", "TBF", "LCIF"],
  image: "/image.png",
};

export const CLIENTS = [
  { name: "Concrete Infra", logo: "/client images/image.png" },
  { name: "VPR Group", logo: "/client images/image copy.png" },
  { name: "Concrete Limelight", logo: "/client images/image copy 2.png" },
  { name: "Phoenix Forever", logo: "/client images/image copy 3.png" },
  { name: "RVR", logo: "/client images/image copy 4.png" },
  { name: "Ravisankar Group", logo: "/client images/image copy 5.png" },
  { name: "Teri School of Advanced Studies", logo: "/client images/image copy 6.png" },
  { name: "Sybaritic Hotel", logo: "/client images/image copy 7.png" },
  { name: "Palm Exotica Boutique Resort & Spa", logo: "/client images/image copy 8.png" },
];
